### ISSUE TITLE
make endpoint to update a user_session_exercises row

### ISSUE THREAD

**Issue by michael-duren** [michael-duren/stickit#62]
api for updating an exercise status during a session

**Comment by Tburnsie10** [comment]
when a user is working on an exercise in a session once they click next session we need a post request to the server to update if it was completed, when it was done, completed tempo, possible other table for notes? updates notes as well, default will be it is not completed wont have date or tempo so we need to update all that once we complete an exercise.
-session_notes for the session written by eric may be useful,

**Comment by Tburnsie10** [comment]
//I dont know how to get COMPLETED_TEMPO and COMPLETED from the front end useStates.
     //optional add in notes to the table
     //here is the fetch inside the console to check it
     /*
      fetch('/api/user/sessions/1/1/', {
      method: "PUT",
      headers: {"Content-Type": "application/json"}})
      */
